/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.team696.MathUtils;

public class MathUtils {
  double linearMap(double x, double in_min, double in_max, double out_min, double out_max) {
    return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
  }

  /**
   * Wraps an angle to (0, 360)
   * 
   * @param angle
   * @return
   */
  double wrapAngle360(double angle) {
    // reduce the angle
    angle = angle % 360;

    // force it to be the positive remainder, so that 0 <= angle < 360
    return (angle + 360) % 360;
  }

  /**
   * Wraps an angle to (-180, 180)
   * 
   * @param angle
   * @return
   */
  double wrapAngle180(double angle) {

    angle = wrapAngle360(angle);
    // force into the minimum absolute value residue class, so that -180 < angle <=
    // 180
    if (angle > 180){
      angle -= 360;
    }
    return angle;
  }
}
