/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.team696.MathUtils;

public class MathUtils {
  public static double linearMap(double x, double in_min, double in_max, double out_min, double out_max) {
    return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
  }

  /**
   * Wraps an angle to (0, 360)
   * 
   * @param angle
   * @return
   */
  public static double wrapAngle360(double angle) {
    // reduce the angle
    angle = angle % 360;

    // force it to be the positive remainder, so that 0 <= angle < 360
    return (angle + 360) % 360;
  }

  /**
   * Wraps an angle to (-180, 180)
   * 
   * @param angle
   * @return
   */
  public static double wrapAngle180(double angle) {

    angle = wrapAngle360(angle);
    // force into the minimum absolute value residue class, so that -180 < angle <=
    // 180
    if (angle > 180){
      angle -= 360;
    }
    return angle;
  }

  public static double deadBand(double x, double deadbandWidth){
  if(x < deadbandWidth){
    return 0;
  }
  return linearMap(x, deadbandWidth, 1, 0, 1);
  }

  /**
   * Converts inches to metric
   * @param inches
   * @return
   */
  public static double StM(double inches){
    return inches * 0.0254;
  }

  /**
   * Converts metric to inches
   * @param metric
   * @return
   */
  public static double MtS(double metric){
    return metric / 0.0254;
  }
}